### ISSUE TITLE
Modulate relay on-off following on command from Homebridge.

### ISSUE THREAD

**Issue by phenotypic** [affix/homebridge-mcu-lamp#8]
Hey there,

I really appreciate the work you've put into this plugin and it's been working perfectly for me! So much so that I want to expand its usage even further. I currently have it controlling a solenoid valve for a new section of my sprinklers and it works a treat. 
However, I now want to use it to control a spray system which I would like to turn on from the Home app and then for the relay to be on for around 3 seconds and then turn off for 5 seconds and repeat this constantly whilst the Home app says it's on and then for the relay to turn off completely as per usual when the off command is given by Homebridge. 

I understand that this is can be achieved by modifying the "ESP8266-Lamp.ino" script; however, I have **very** little experience with programming in C as I am more of a Bash scripting person. I would really appreciate it if someone could help me out by letting me know what to change inside the script.

Thank you in advance for any help,
Kind Regards,
Tom

**Comment by Tommrodrigues** [comment]
No worries, I was eventually able to implement this feature by myself in my [homebridge-nodemcu-relay](https://github.com/Tommrodrigues/homebridge-nodemcu-relay) project. Thanks!
